### ISSUE TITLE
ToDo v1

### ISSUE THREAD

**Issue by aaroniker** [aaroniker/imscp-next#1]
Reported here https://i-mscp.net/thread/18235-new-custom-theme/?postID=62906#post62906
(still growing)

## Errors
- [ ]  400 /admin/manage_reseller_owners.php
- [ ]  400 /admin/manage_reseller_users.php
- [ ]  ~~400 /client/software.php~~ [can be ignored as said here](https://i-mscp.net/thread/18235-new-custom-theme/?postID=62902#post62902)
## Markup
- [x] /admin/domain_details.php
- [x]  /admin/ip_manage.php
- [x]  /admin/settings_lostpassword.php
- [x]  /admin/settings_ports.php
- [x]  /admin/settings_plugins.php
- [x]  /reseller/alias.php
- [ ]  /reseller/settings_welcome_mail.php
- [ ]  /reseller/settings_lostpassword.php
- [ ]  /reseller/hosting_plan.php
- [ ]  /reseller/hosting_plan_add.php
- [ ]  /reseller/hosting_plan_edit.php
- [ ]  /reseller/user_statistics.php
- [ ]  /reseller/ip_usage.php
- [ ]  /reseller/ticket_create.php
- [ ]  /reseller/domain_edit.php
- [ ]  /reseller/domain_details.php
- [ ]  /reseller/user_add2.php
- [x]  /client/dns_edit.php
- [x]  /client/mail_accounts.php (Desktop done, mobile WIP)
- [x]  /client/mail_add.php
- [x] /client/mail_autoresponder_edit.php
- [x]  /client/mail_catchall.php
- [x]  /client/mail_catchall_add.php
- [x]  /client/mail_external.php
- [ ]  /client/traffic_statistics.php
- [ ]  /client/webtools.php
- [ ]  /client/error_pages.php
- [ ]  /client/backup.php
- [ ]  /client/ticket_create.php
- [ ]  /client/alias_edit.php
- [ ]  /client/domain_edit.php
- [ ]  /client/subdomain_edit.php
- [x]  /client/mail_edit.php
- [ ]  ~~/admin/software_manage.php~~ [can be ignored as said here](https://i-mscp.net/thread/18235-new-custom-theme/?postID=62902#post62902)
- [ ]  ~~/reseller/software_upload.php~~ [can be ignored as said here](https://i-mscp.net/thread/18235-new-custom-theme/?postID=62902#post62902)
## Misc
- [ ]  The button for the previous login / user (if you choose to switch to another user) looks odd. Theres just the name of the "real" account. It should be named like "back to * account" or similar to the current design name thing for it.

**Comment by theemstra** [comment]
The LetsEncypt page is also left to do (table), the buttons there don't work and cause JS errors:

"Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'refresh'"

**Comment by aaroniker** [comment]
@theemstra thank you! isn't that a plugin page?
these are not high prio atm - ill try to pick up the theme again the next 1-2 weeks
